### ISSUE TITLE
Allow 32 bit option

### ISSUE THREAD

**Issue by kdheepak** [goanpeca/setup-miniconda#10]
https://github.com/goanpeca/setup-miniconda/blob/bde5ac1a373f18066038802241b6bf0ccf747d8a/src/main.ts#L25

Currently, it always defaults to 64 bit. It would be nice to use this to build and test conda 32 bit packages on Windows.

**Comment by goanpeca** [comment]
Yes, is on my todo list ;-)

**Comment by bryanwweber** [comment]
What needs to be done to enable this? Is it as simple as adding a `architecture` option to the `core.getInput()` calls in `run()` and replacing the line shown above? I would be happy to take a shot at it, if it is that easy.

**Comment by goanpeca** [comment]
Hi @bryanwweber, thanks for the interest. So yes in theory.. but in practice there might be some errors that pop up, feel free to tackle this one :-)
