### ISSUE TITLE
Use miniconda with other actions

### ISSUE THREAD

**Issue by Maarten-vd-Sande** [goanpeca/setup-miniconda#12]
I'm trying to setup my first GitHub Actions workflow, but I am having troubles getting it to work in combination with other actions. I couldn't find an example of this, and I am not even sure if it's supposed to work. In my case I am trying to combine the code coverage action with the miniconda environment I made:

    - name: Setup Miniconda
      uses: goanpeca/setup-miniconda@v1.0.2
      with:
       activate-environment: peaksql
       environment-file: environment.yml
       python-version: ${{ matrix.python-version }}

    - name: Test & publish code coverage
      env:
        CC_TEST_REPORTER_ID: ${{secrets.CodeCoverage}}
      uses: paambaati/codeclimate-action@v2.4.0
      with:
        coverageCommand: coverage run -m unittest discover test
        debug: true

Adding  `shell: bash -l {0}` gives the error:

> shell cannot be used with `uses`, `with`

Is it possible to combine setup-miniconda with other actions? If so, how?

**Comment by goanpeca** [comment]
From the error it seems no it is not possible at least with bash since a “special” shell is needed. One option would be to use powershell core (which do no require the special shell ... argument

**Comment by Maarten-vd-Sande** [comment]
I didn't get it to work. Thanks for your answer!

**Comment by Maarten-vd-Sande** [comment]
@goanpeca how do I make use of powershell in this case? Can we set a default shell in github actions?

**Comment by goanpeca** [comment]
You have to do it per step. Look on the readme.

**Comment by Maarten-vd-Sande** [comment]
Yes but when I try to add it to the step `Test & publish code coverage` github actions complains that 

> shell cannot be used with `uses`, `with`

**Comment by goanpeca** [comment]
Then it cannot be done 🤷🏻‍♂️
