### ISSUE TITLE
Channels option (README ex. 4) not working (not found)

### ISSUE THREAD

**Issue by sadielbartholomew** [goanpeca/setup-miniconda#19]
Hi, I am trying to use your Action for a project I co-develop, 'cf-python'. However, it is not working as documented when I try to access the variant of the Action with channels available (as I need to use channels), namely 'Example 4: Conda options' from the README. In particular, my job fails after repeatedly trying & failing to download the Action ``goanpeca/setup-miniconda@enh/channels`` itself:

```bash
Failed to download action 'https://api.github.com/repos/goanpeca/setup-miniconda/tarball/enh/channels'. Error Response status code does not indicate success: 404 (Not Found).
```

(you can view the job in question [here](https://github.com/NCAS-CMS/cf-python/actions/runs/72697526) if that helps.)

When I try this in the URL, the component before the '@' symbol is picked up, but looking at this repo there does not seem to be a ``enh/channels`` branch. I see there's a ``enh/rever`` branch but looking at it it does not seem to be the same thing under a different name as far as I can tell.

Should the channels option Action variant work as far as you know? If not, it would be helpful if you removed it to prevent users like myself trying it out in vain, & could you please advise as to whether there is a way to access channels somehow using this Action, as without these it will be more difficult for me to setup a desired custom Action on my project.

Thanks.

**Comment by goanpeca** [comment]
It is not released yet but is available if you use with

@master

Or @1.x 

Sorry for the inconvenience, I will be making a new release soon.

**Comment by goanpeca** [comment]
Also take into account that this is the development repo. The actual current releases can be found by looking at the repo tags or by looking at the marketplace directly. All projects work like this and by visiting  the repo directly you are most likely seeing things not yet available.

**Comment by sadielbartholomew** [comment]
Ah, I see thank you, & sorry for picking up on that. You are right, it is standard practice. I think I got a bit excited seeing the channels option as it will make my life very easy wrt the exact Actions workflow I want! So I didn't think to check whether it was released.

> Sorry for the inconvenience, I will be making a new release soon.

No need to apologise, it was my bad. I'll close this.

Any idea how long it might take before the new release is out? If it might be a while I can try and use the functionality you have in the current release to install what I need without using channels. It will be a bit more difficult but still possible, hopefully. Otherwise I will wait.

**Comment by goanpeca** [comment]
It might go out today, I just need to find some time to do it.

**Comment by sadielbartholomew** [comment]
> It might go out today, I just need to find some time to do it.

Oh, excellent. Anytime in the next week or two would work for me, & it sounds like you will release in that timescale. Thanks @goanpeca!

**Comment by goanpeca** [comment]
Hi @sadielbartholomew. Just made the release. Let me know how it goes.

**Comment by sadielbartholomew** [comment]
Wonderful, thank you @goanpeca. This is a really useful Action so thanks for creating & maintaining it.

**Comment by goanpeca** [comment]
Thanks for using it :-)
