### ISSUE TITLE
How to use it with other github actions

### ISSUE THREAD

**Issue by melund** [goanpeca/setup-miniconda#24]
I tried to use this with an other github action that builds and checks sphinx documentation. 

https://github.com/marketplace/actions/sphinx-build

Of course it didn't pick up the activated environment, so the build failed. I can get it working if I run the shell directly with ``shell: bash -l {0}``. 

But the [sphinx-build](https://github.com/marketplace/actions/sphinx-build
) action has some nice features which I like to use. 

It does provide a way to run a pre build command. Can that be used to activate the conda-environment? 

```
      - uses: ammaraskar/sphinx-action@master
        with:
          pre-build-command: ..XXXXXX...
```
I once did something similar in the gitlab ci system where I ran   ``. /opt/conda/etc/profile.d/conda.sh && conda activate sphinx"`` to get the environment activated. Could I do something similar here?

**Comment by skearnes** [comment]
If you add an action to update the PATH in a persistent manner, you won't need the `shell: bash -l {0}` incantation:

```
- name: Update PATH
    shell: bash -l {0}
    run: echo "::add-path::$(dirname $(which conda))"
```

Future actions will now have access to conda without specifying the `shell` argument. See the [actions documentation](https://help.github.com/en/actions/reference/workflow-commands-for-github-actions#adding-a-system-path) for more.

**Comment by goanpeca** [comment]
@skearnes conda activations may do more than just setting the path.

**Comment by skearnes** [comment]
Fair enough; do you have a suggestion for how to avoid the `shell` setting? It's annoying and error-prone to have to carry it over to all subsequent steps.

**Comment by goanpeca** [comment]
>do you have a suggestion for how to avoid the shell setting?

Ask github for a shell option that can be set globally per job  🤷 

>It's annoying and error-prone to have to carry it over to all subsequent steps.

I know... but not much I can do about it at the moment if we want conda to work properly.

**Comment by skearnes** [comment]
FYI https://github.com/marketplace/actions/setup-conda seems to handle this. I think they're using the GitHub typescript libraries to modify the PATH.

**Comment by goanpeca** [comment]
@skearnes that action does not correctly activate conda environments.

**Comment by goanpeca** [comment]
>FYI https://github.com/marketplace/actions/setup-conda seems to handle this. I think they're using the GitHub typescript libraries to modify the PATH.

As I stated above, modifying the PATH is not enough to have a working conda environment, or a correctly activated one.

**Comment by goanpeca** [comment]
@melund if you have the opportunity to run a command I think you can use something like:

```bash
eval "$(conda shell.bash hook)"; conda activate <env-name>;
```

**Comment by melund** [comment]
@goanpeca Thanks a lot. I had indeed the option of running a pre-command.  I will try your suggestion.
