### ISSUE TITLE
Conda env and condabin paths are not put at front of PATH in macOS

### ISSUE THREAD

**Issue by ccordoba12** [goanpeca/setup-miniconda#26]
They are put after `/usr/bin`, `/usr/local/bin`, etc.

See https://github.com/spyder-ide/spyder/pull/12389 for details.

**Comment by skearnes** [comment]
Might be helpful: https://github.com/goanpeca/setup-miniconda/issues/24#issuecomment-618733459

**Comment by goanpeca** [comment]
@ccordoba12 

I cannot see that behavior:

https://github.com/goanpeca/setup-miniconda/pull/29/checks?check_run_id=654696533#step:4:89

**Comment by goanpeca** [comment]
Maybe because we call a script  like:

`run: bash -l .github/scripts/install.sh`

But there is nothing I can do here, since without calling scripts the path is just fine as you can see on [the PR](https://github.com/goanpeca/setup-miniconda/pull/29)

**Comment by ccordoba12** [comment]
Why PATH is scrambled after calling a script?

**Comment by goanpeca** [comment]
>Why PATH is scrambled after calling a script?

No idea
