### ISSUE TITLE
How to use with cache mechanism?

### ISSUE THREAD

**Issue by esheldon** [goanpeca/setup-miniconda#27]
Thanks for this, I'm finding it very useful.

Is it possible to cache the miniconda3 setup using actions/cache?  I think all I need is a path to the miniconda3 directory, but I'm not sure where that would be in the container.

**Comment by goanpeca** [comment]
There is an Environment Variable `CONDA` which points to the folder where miniconda is installed.

You could try using that? Your mileage may vary!

Cheers

**Comment by goanpeca** [comment]
@esheldon 

Added support for caching. Please see https://github.com/marketplace/actions/setup-miniconda

Thanks!

**Comment by esheldon** [comment]
Awesome, I'll check it out.  thanks

**Comment by goanpeca** [comment]
👍
