### ISSUE TITLE
No such file or directory, scandir '/home/runner/conda_pkgs_dir'

### ISSUE THREAD

**Issue by mksenzov** [goanpeca/setup-miniconda#36]
Thank you for an awesome GitHub workflow / conda integration, has been using it for a little while and it is super helpful.

Starting today (15/05/2019) I noticed a bunch of CIs failed in ` Run goanpeca/setup-miniconda@v1` with: 

```
Append to "/home/runner/.xonshrc":
 
# ----------------------------------------------------------------------------
# Conda Setup Action: Basic configuration
set -eo pipefail
# Conda Setup Action: Custom activation
conda activate my_env
# ---------------------------------------------------------------------------- 

Append to "/home/runner/.config/powershell/profile.ps1":
 
# ----------------------------------------------------------------------------
# Conda Setup Action: Custom activation
conda activate my_env
# ---------------------------------------------------------------------------- 


# Removing uncompressed packages to trim down cache folder...
##[error]ENOENT: no such file or directory, scandir '/home/runner/conda_pkgs_dir'
```

An example workflow where I can repro:

```
  build:
    runs-on: ubuntu-latest

...

    - uses: goanpeca/setup-miniconda@v1
      with:
        activate-environment: my_env

```

It appears to be related to the new release 1.3.0 which was pushed just yesterday; when I locked version to `goanpeca/setup-miniconda@v1.2.0` the builds resumed successfully.

**Comment by goanpeca** [comment]
Hi @mksenzov, thanks for the report. It seems like a regression. Will make a new release to fix this tomorrow.

Cheers!

**Comment by goanpeca** [comment]
@mksenzov could you check that using 

`goanpeca/setup-miniconda@fix/cache-folder-removal` fixes the issue?

Thanks!

**Comment by mksenzov** [comment]
@goanpeca just gave it a go, the build works now, tyvm for fixing!

**Comment by goanpeca** [comment]
Ok, will make the release now, should be available in 30 minutes or so.

I normally point the v1 to the latest v1.x version (I think I read that somewhere as recommended)

Need to add tests to this to avoid this on the future.

Cheers!

**Comment by goanpeca** [comment]
@mksenzov released!
