### ISSUE TITLE
The action stopped working a few minutes ago

### ISSUE THREAD

**Issue by mwouts** [goanpeca/setup-miniconda#40]
Hello @goanpeca ,

First of all, thanks for your GitHub Action - it was really helpful when I switched my CI to GitHub Actions a few weeks ago (cf. my [related article in TDS](https://towardsdatascience.com/testing-your-python-project-with-github-actions-ec9bf82b20dc)).

Very recently I've seen my miniconda jobs failing with error messages like this one:
> An action could not be found at the URI 'https://api.github.com/repos/goanpeca/setup-miniconda/tarball/v1'

See for instance [this build](https://github.com/mwouts/jupytext/actions/runs/112570601), which was the first one to show the issue.

Do you know how to fix this? I've restarted the build, and then tried to take v1.4, but it did not work.

**Comment by goanpeca** [comment]
@mwouts thanks for the report.

I also noticed this, I just made a new release and it seems github takes some time to recreate the tarball once the tag was made. I restarted my builds, and everything worked fine.

Could you try again?

**Comment by mwouts** [comment]
I see! Indeed, [this run](https://github.com/mwouts/jupytext/actions/runs/112601494) just started and seems OK. Thank you, and sorry for the false positive :smiley:

**Comment by goanpeca** [comment]
@mwouts nice article! Maybe you could update it to include caching :-) 

Cheers!

**Comment by mwouts** [comment]
Sure, I will! Thanks for letting me know about it!

**Comment by mwouts** [comment]
Hello Gonzalo, for you information I am giving a try to the cache at https://github.com/mwouts/jupytext/pull/515 :smile:
