### ISSUE TITLE
conda build support?

### ISSUE THREAD

**Issue by bobfang1992** [goanpeca/setup-miniconda#50]
Hi,

Sorry this may be very stupid, but is `conda build` supported by this? Thanks a lot!

Bob

**Comment by goanpeca** [comment]
Hi @bobfang1992 

See https://github.com/goanpeca/setup-miniconda/blob/master/action.yml#L17

**Comment by bobfang1992** [comment]
Great thanks!

**Comment by fabiencelier** [comment]
Nice, I've missed this link while reading the doc
