### ISSUE TITLE
CondaValueError in Microconda setup

### ISSUE THREAD

**Issue by Borda** [goanpeca/setup-miniconda#51]
Hi, thx for this nice tool, just need some help to let it run...
My use case is to restore packages according to given `environment.yaml` file, so I followed your example, but I am getting its strange error
```
/usr/share/miniconda3/condabin/conda env create -f environment.yml
##[warning]
CondaValueError: prefix already exists: /usr/share/miniconda3

CondaValueError: prefix already exists: /usr/share/miniconda3

##[error]The process '/usr/share/miniconda3/condabin/conda' failed with exit code 1
```
the full run you can find here https://github.com/PyTorchLightning/pytorch-lightning/pull/2412/checks?check_run_id=821315545
also with the cat of actual config file...

**Comment by goanpeca** [comment]
Hi @Borda. So your environment.yaml needs to define a `name` key and that name key must match the "activate-environment" option in the action.

**Comment by Borda** [comment]
@goanpeca thx for a fast reply, just thinking that it would be smoother when the action would define apply the `activate-environment` if key `name` is missing in YAML... 
just to give my context, if we add the `name` to the YAML we force the user to use the very same name unless he manually changes it wich I would say not very nice to user... does it make sense for you?

**Comment by goanpeca** [comment]
>just to give my context, if we add the name to the YAML we force the user to use the very same name unless he manually changes it wich I would say not very nice to user... does it make sense for you?

Yes, that would be nicer on the user, but is kinda magic. I will meditate on it. You should have still received a warning that the names did not match in that action step. Was not the case?

**Comment by Borda** [comment]
yes, at least add a bit more understandable message what is wrong because without your help I would not be able to resolve it... maybe also add this info to readme? send a PR?
