### ISSUE TITLE
Teardown failure when deleting files

### ISSUE THREAD

**Issue by martindurant** [goanpeca/setup-miniconda#63]
See https://github.com/dask/dask/pull/6528/checks?check_run_id=1003538612#step:11:32

Tests pass, but cleanup (Post Setup Conda Environment) fails when deleting files.

Seen on Windows.

**Comment by goanpeca** [comment]
Thanks @martindurant for the report.

Will try to catch these errors (not sure why that file would fail to be removed 🤷 ).
