### ISSUE TITLE
Problem with environment file

### ISSUE THREAD

**Issue by epassaro** [goanpeca/setup-miniconda#7]
Hi! I can't create my env with a YML file located at the top of my GitHub repository. I don't know what I'm doing wrong. Tried a lot of combinations but always end with this NOENT error.

`##[error]ENOENT: no such file or directory, open '/home/runner/work/gh_actions/gh_actions/tardis_env3.yml'`

**Comment by goanpeca** [comment]
Please share your yaml file

**Comment by epassaro** [comment]
Sorry, forgot to add `uses: actions/checkout@v2`. Solved.

Thanks.

**Comment by goanpeca** [comment]
Glad you solved it, I will add a FAQ to add this information ;-)
